// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: warehouse_v1.proto

package warehousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для создания склада
type CreateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                         // Адрес
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`                               // Город
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`                         // Страна
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"` // Почтовый индекс (опционально)
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`                             // Телефон (опционально)
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`      // Активен ли склад
	Capacity      uint32                 `protobuf:"varint,7,opt,name=capacity,proto3" json:"capacity,omitempty"`                      // Вместимость
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                 // Описание
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseRequest) Reset() {
	*x = CreateWarehouseRequest{}
	mi := &file_warehouse_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseRequest) ProtoMessage() {}

func (x *CreateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*CreateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWarehouseRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateWarehouseRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateWarehouseRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateWarehouseRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateWarehouseRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateWarehouseRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateWarehouseRequest) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateWarehouseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Сообщение для обновления склада
type UpdateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // ID склада
	Address       *string                `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`                         // Адрес
	City          *string                `protobuf:"bytes,3,opt,name=city,proto3,oneof" json:"city,omitempty"`                               // Город
	Country       *string                `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`                         // Страна
	PostalCode    *string                `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"` // Почтовый индекс
	Phone         *string                `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`                             // Телефон
	IsActive      *bool                  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`      // Активен ли склад
	Capacity      *uint32                `protobuf:"varint,8,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`                      // Вместимость
	Description   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`                 // Описание
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseRequest) Reset() {
	*x = UpdateWarehouseRequest{}
	mi := &file_warehouse_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseRequest) ProtoMessage() {}

func (x *UpdateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateWarehouseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWarehouseRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateWarehouseRequest) GetCapacity() uint32 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *UpdateWarehouseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// Основное сообщение для представления склада
type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // Уникальный идентификатор
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                         // Адрес
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`                               // Город
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`                         // Страна
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"` // Почтовый индекс
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                             // Телефон
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`      // Активен ли склад
	Capacity      uint32                 `protobuf:"varint,8,opt,name=capacity,proto3" json:"capacity,omitempty"`                      // Вместимость
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`                 // Описание
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`   // Дата создания
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`   // Дата обновления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_warehouse_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Warehouse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Warehouse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Warehouse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Warehouse) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Warehouse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Warehouse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Warehouse) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Warehouse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Warehouse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Warehouse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Сообщение для получения склада по ID
type GetWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID склада
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseRequest) Reset() {
	*x = GetWarehouseRequest{}
	mi := &file_warehouse_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseRequest) ProtoMessage() {}

func (x *GetWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseRequest.ProtoReflect.Descriptor instead.
func (*GetWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetWarehouseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Сообщение для получения списка складов
type ListWarehousesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // Номер страницы
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                       // Количество элементов на странице
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // Фильтр по активности
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`                    // Фильтр по стране
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`                          // Фильтр по городу
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesRequest) Reset() {
	*x = ListWarehousesRequest{}
	mi := &file_warehouse_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesRequest) ProtoMessage() {}

func (x *ListWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesRequest.ProtoReflect.Descriptor instead.
func (*ListWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ListWarehousesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWarehousesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWarehousesRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListWarehousesRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListWarehousesRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// Ответ со списком складов
type ListWarehousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`                    // Список складов
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Общее количество складов
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                               // Текущая страница
	TotalPages    uint32                 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // Общее количество страниц
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesResponse) Reset() {
	*x = ListWarehousesResponse{}
	mi := &file_warehouse_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesResponse) ProtoMessage() {}

func (x *ListWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesResponse.ProtoReflect.Descriptor instead.
func (*ListWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ListWarehousesResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

func (x *ListWarehousesResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListWarehousesResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWarehousesResponse) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Сообщение для удаления склада (мягкое удаление)
type DeleteWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID склада
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehouseRequest) Reset() {
	*x = DeleteWarehouseRequest{}
	mi := &file_warehouse_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehouseRequest) ProtoMessage() {}

func (x *DeleteWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehouseRequest.ProtoReflect.Descriptor instead.
func (*DeleteWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWarehouseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Пустой ответ
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_warehouse_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_v1_proto_rawDescGZIP(), []int{7}
}

var File_warehouse_v1_proto protoreflect.FileDescriptor

const file_warehouse_v1_proto_rawDesc = "" +
	"\n" +
	"\x12warehouse_v1.proto\x12\fwarehouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\x16CreateWarehouseRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1a\n" +
	"\bcapacity\x18\a \x01(\rR\bcapacity\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\x90\x03\n" +
	"\x16UpdateWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\aaddress\x18\x02 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x03 \x01(\tH\x01R\x04city\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x04 \x01(\tH\x02R\acountry\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x05 \x01(\tH\x03R\n" +
	"postalCode\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x04R\x05phone\x88\x01\x01\x12 \n" +
	"\tis_active\x18\a \x01(\bH\x05R\bisActive\x88\x01\x01\x12\x1f\n" +
	"\bcapacity\x18\b \x01(\rH\x06R\bcapacity\x88\x01\x01\x12%\n" +
	"\vdescription\x18\t \x01(\tH\aR\vdescription\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_countryB\x0e\n" +
	"\f_postal_codeB\b\n" +
	"\x06_phoneB\f\n" +
	"\n" +
	"_is_activeB\v\n" +
	"\t_capacityB\x0e\n" +
	"\f_description\"\xeb\x02\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1a\n" +
	"\bcapacity\x18\b \x01(\rR\bcapacity\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"%\n" +
	"\x13GetWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8c\x01\n" +
	"\x15ListWarehousesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\"\xa7\x01\n" +
	"\x16ListWarehousesResponse\x127\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x17.warehouse.v1.WarehouseR\n" +
	"warehouses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\rR\n" +
	"totalPages\"(\n" +
	"\x16DeleteWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0f\n" +
	"\rEmptyResponse2\xb7\x03\n" +
	"\x12WarehouseV1Service\x12P\n" +
	"\x0fCreateWarehouse\x12$.warehouse.v1.CreateWarehouseRequest\x1a\x17.warehouse.v1.Warehouse\x12J\n" +
	"\fGetWarehouse\x12!.warehouse.v1.GetWarehouseRequest\x1a\x17.warehouse.v1.Warehouse\x12P\n" +
	"\x0fUpdateWarehouse\x12$.warehouse.v1.UpdateWarehouseRequest\x1a\x17.warehouse.v1.Warehouse\x12[\n" +
	"\x0eListWarehouses\x12#.warehouse.v1.ListWarehousesRequest\x1a$.warehouse.v1.ListWarehousesResponse\x12T\n" +
	"\x0fDeleteWarehouse\x12$.warehouse.v1.DeleteWarehouseRequest\x1a\x1b.warehouse.v1.EmptyResponseB(Z&pkg/warehouse/warehouse_v1;warehousev1b\x06proto3"

var (
	file_warehouse_v1_proto_rawDescOnce sync.Once
	file_warehouse_v1_proto_rawDescData []byte
)

func file_warehouse_v1_proto_rawDescGZIP() []byte {
	file_warehouse_v1_proto_rawDescOnce.Do(func() {
		file_warehouse_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warehouse_v1_proto_rawDesc), len(file_warehouse_v1_proto_rawDesc)))
	})
	return file_warehouse_v1_proto_rawDescData
}

var file_warehouse_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_warehouse_v1_proto_goTypes = []any{
	(*CreateWarehouseRequest)(nil), // 0: warehouse.v1.CreateWarehouseRequest
	(*UpdateWarehouseRequest)(nil), // 1: warehouse.v1.UpdateWarehouseRequest
	(*Warehouse)(nil),              // 2: warehouse.v1.Warehouse
	(*GetWarehouseRequest)(nil),    // 3: warehouse.v1.GetWarehouseRequest
	(*ListWarehousesRequest)(nil),  // 4: warehouse.v1.ListWarehousesRequest
	(*ListWarehousesResponse)(nil), // 5: warehouse.v1.ListWarehousesResponse
	(*DeleteWarehouseRequest)(nil), // 6: warehouse.v1.DeleteWarehouseRequest
	(*EmptyResponse)(nil),          // 7: warehouse.v1.EmptyResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_warehouse_v1_proto_depIdxs = []int32{
	8, // 0: warehouse.v1.Warehouse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: warehouse.v1.Warehouse.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: warehouse.v1.ListWarehousesResponse.warehouses:type_name -> warehouse.v1.Warehouse
	0, // 3: warehouse.v1.WarehouseV1Service.CreateWarehouse:input_type -> warehouse.v1.CreateWarehouseRequest
	3, // 4: warehouse.v1.WarehouseV1Service.GetWarehouse:input_type -> warehouse.v1.GetWarehouseRequest
	1, // 5: warehouse.v1.WarehouseV1Service.UpdateWarehouse:input_type -> warehouse.v1.UpdateWarehouseRequest
	4, // 6: warehouse.v1.WarehouseV1Service.ListWarehouses:input_type -> warehouse.v1.ListWarehousesRequest
	6, // 7: warehouse.v1.WarehouseV1Service.DeleteWarehouse:input_type -> warehouse.v1.DeleteWarehouseRequest
	2, // 8: warehouse.v1.WarehouseV1Service.CreateWarehouse:output_type -> warehouse.v1.Warehouse
	2, // 9: warehouse.v1.WarehouseV1Service.GetWarehouse:output_type -> warehouse.v1.Warehouse
	2, // 10: warehouse.v1.WarehouseV1Service.UpdateWarehouse:output_type -> warehouse.v1.Warehouse
	5, // 11: warehouse.v1.WarehouseV1Service.ListWarehouses:output_type -> warehouse.v1.ListWarehousesResponse
	7, // 12: warehouse.v1.WarehouseV1Service.DeleteWarehouse:output_type -> warehouse.v1.EmptyResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_warehouse_v1_proto_init() }
func file_warehouse_v1_proto_init() {
	if File_warehouse_v1_proto != nil {
		return
	}
	file_warehouse_v1_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warehouse_v1_proto_rawDesc), len(file_warehouse_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warehouse_v1_proto_goTypes,
		DependencyIndexes: file_warehouse_v1_proto_depIdxs,
		MessageInfos:      file_warehouse_v1_proto_msgTypes,
	}.Build()
	File_warehouse_v1_proto = out.File
	file_warehouse_v1_proto_goTypes = nil
	file_warehouse_v1_proto_depIdxs = nil
}
