// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: product_v1.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku              string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	PriceOld         float64                `protobuf:"fixed64,7,opt,name=price_old,json=priceOld,proto3" json:"price_old,omitempty"`
	Discount         float64                `protobuf:"fixed64,8,opt,name=discount,proto3" json:"discount,omitempty"`
	Quantity         uint32                 `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive         bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Brand            string                 `protobuf:"bytes,11,opt,name=brand,proto3" json:"brand,omitempty"`
	Rating           float64                `protobuf:"fixed64,12,opt,name=rating,proto3" json:"rating,omitempty"`
	CategoryId       uint32                 `protobuf:"varint,13,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetPriceOld() float64 {
	if x != nil {
		return x.PriceOld
	}
	return 0
}

func (x *Product) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Product) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Product) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

// CreateProduct Request and Response
type CreateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sku              string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	ShortDescription string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	PriceOld         float64                `protobuf:"fixed64,6,opt,name=price_old,json=priceOld,proto3" json:"price_old,omitempty"`
	Discount         float64                `protobuf:"fixed64,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Quantity         uint32                 `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive         bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Brand            string                 `protobuf:"bytes,10,opt,name=brand,proto3" json:"brand,omitempty"`
	Rating           float64                `protobuf:"fixed64,11,opt,name=rating,proto3" json:"rating,omitempty"`
	CategoryId       uint32                 `protobuf:"varint,12,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetPriceOld() float64 {
	if x != nil {
		return x.PriceOld
	}
	return 0
}

func (x *CreateProductRequest) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreateProductRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_product_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResponse) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// UpdateProduct Request and Response
type UpdateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku              string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	PriceOld         float64                `protobuf:"fixed64,7,opt,name=price_old,json=priceOld,proto3" json:"price_old,omitempty"`
	Discount         float64                `protobuf:"fixed64,8,opt,name=discount,proto3" json:"discount,omitempty"`
	Quantity         uint32                 `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive         bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Brand            string                 `protobuf:"bytes,11,opt,name=brand,proto3" json:"brand,omitempty"`
	Rating           float64                `protobuf:"fixed64,12,opt,name=rating,proto3" json:"rating,omitempty"`
	CategoryId       uint32                 `protobuf:"varint,13,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateProductRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetPriceOld() float64 {
	if x != nil {
		return x.PriceOld
	}
	return 0
}

func (x *UpdateProductRequest) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *UpdateProductRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateProductRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateProductRequest) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_product_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductResponse) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// DeleteProduct Request and Response
type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_product_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductResponse) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// Get all products
type GetAllProductsByQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsByQueryRequest) Reset() {
	*x = GetAllProductsByQueryRequest{}
	mi := &file_product_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsByQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsByQueryRequest) ProtoMessage() {}

func (x *GetAllProductsByQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsByQueryRequest.ProtoReflect.Descriptor instead.
func (*GetAllProductsByQueryRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllProductsByQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetAllProductsByQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsByQueryResponse) Reset() {
	*x = GetAllProductsByQueryResponse{}
	mi := &file_product_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsByQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsByQueryResponse) ProtoMessage() {}

func (x *GetAllProductsByQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsByQueryResponse.ProtoReflect.Descriptor instead.
func (*GetAllProductsByQueryResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllProductsByQueryResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Get product
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       []*Product             `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_product_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductResponse) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_product_v1_proto protoreflect.FileDescriptor

const file_product_v1_proto_rawDesc = "" +
	"\n" +
	"\x10product_v1.proto\x12\n" +
	"product.v1\"\xe5\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12+\n" +
	"\x11short_description\x18\x04 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1b\n" +
	"\tprice_old\x18\a \x01(\x01R\bpriceOld\x12\x1a\n" +
	"\bdiscount\x18\b \x01(\x01R\bdiscount\x12\x1a\n" +
	"\bquantity\x18\t \x01(\rR\bquantity\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x14\n" +
	"\x05brand\x18\v \x01(\tR\x05brand\x12\x16\n" +
	"\x06rating\x18\f \x01(\x01R\x06rating\x12\x1f\n" +
	"\vcategory_id\x18\r \x01(\rR\n" +
	"categoryId\"\xe2\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1b\n" +
	"\tprice_old\x18\x06 \x01(\x01R\bpriceOld\x12\x1a\n" +
	"\bdiscount\x18\a \x01(\x01R\bdiscount\x12\x1a\n" +
	"\bquantity\x18\b \x01(\rR\bquantity\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\tR\x05brand\x12\x16\n" +
	"\x06rating\x18\v \x01(\x01R\x06rating\x12\x1f\n" +
	"\vcategory_id\x18\f \x01(\rR\n" +
	"categoryId\"5\n" +
	"\x15CreateProductResponse\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\"\x80\x03\n" +
	"\x14UpdateProductRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12+\n" +
	"\x11short_description\x18\x04 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1b\n" +
	"\tprice_old\x18\a \x01(\x01R\bpriceOld\x12\x1a\n" +
	"\bdiscount\x18\b \x01(\x01R\bdiscount\x12\x1a\n" +
	"\bquantity\x18\t \x01(\rR\bquantity\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x14\n" +
	"\x05brand\x18\v \x01(\tR\x05brand\x12\x16\n" +
	"\x06rating\x18\f \x01(\x01R\x06rating\x12\x1f\n" +
	"\vcategory_id\x18\r \x01(\rR\n" +
	"categoryId\"5\n" +
	"\x15UpdateProductResponse\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\"4\n" +
	"\x14DeleteProductRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\"5\n" +
	"\x15DeleteProductResponse\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\"4\n" +
	"\x1cGetAllProductsByQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"P\n" +
	"\x1dGetAllProductsByQueryResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\"1\n" +
	"\x11GetProductRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\"C\n" +
	"\x12GetProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x03(\v2\x13.product.v1.ProductR\aproduct2\x82\x03\n" +
	"\x10ProductV1Service\x12T\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponse\x12l\n" +
	"\x15GetAllProductsByQuery\x12(.product.v1.GetAllProductsByQueryRequest\x1a).product.v1.GetAllProductsByQueryResponse\x12T\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a!.product.v1.UpdateProductResponse\x12T\n" +
	"\rDeleteProduct\x12 .product.v1.DeleteProductRequest\x1a!.product.v1.DeleteProductResponseB\"Z pkg/product/product_v1;productv1b\x06proto3"

var (
	file_product_v1_proto_rawDescOnce sync.Once
	file_product_v1_proto_rawDescData []byte
)

func file_product_v1_proto_rawDescGZIP() []byte {
	file_product_v1_proto_rawDescOnce.Do(func() {
		file_product_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_proto_rawDesc), len(file_product_v1_proto_rawDesc)))
	})
	return file_product_v1_proto_rawDescData
}

var file_product_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_v1_proto_goTypes = []any{
	(*Product)(nil),                       // 0: product.v1.Product
	(*CreateProductRequest)(nil),          // 1: product.v1.CreateProductRequest
	(*CreateProductResponse)(nil),         // 2: product.v1.CreateProductResponse
	(*UpdateProductRequest)(nil),          // 3: product.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),         // 4: product.v1.UpdateProductResponse
	(*DeleteProductRequest)(nil),          // 5: product.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil),         // 6: product.v1.DeleteProductResponse
	(*GetAllProductsByQueryRequest)(nil),  // 7: product.v1.GetAllProductsByQueryRequest
	(*GetAllProductsByQueryResponse)(nil), // 8: product.v1.GetAllProductsByQueryResponse
	(*GetProductRequest)(nil),             // 9: product.v1.GetProductRequest
	(*GetProductResponse)(nil),            // 10: product.v1.GetProductResponse
}
var file_product_v1_proto_depIdxs = []int32{
	0, // 0: product.v1.GetAllProductsByQueryResponse.products:type_name -> product.v1.Product
	0, // 1: product.v1.GetProductResponse.product:type_name -> product.v1.Product
	1, // 2: product.v1.ProductV1Service.CreateProduct:input_type -> product.v1.CreateProductRequest
	7, // 3: product.v1.ProductV1Service.GetAllProductsByQuery:input_type -> product.v1.GetAllProductsByQueryRequest
	3, // 4: product.v1.ProductV1Service.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	5, // 5: product.v1.ProductV1Service.DeleteProduct:input_type -> product.v1.DeleteProductRequest
	2, // 6: product.v1.ProductV1Service.CreateProduct:output_type -> product.v1.CreateProductResponse
	8, // 7: product.v1.ProductV1Service.GetAllProductsByQuery:output_type -> product.v1.GetAllProductsByQueryResponse
	4, // 8: product.v1.ProductV1Service.UpdateProduct:output_type -> product.v1.UpdateProductResponse
	6, // 9: product.v1.ProductV1Service.DeleteProduct:output_type -> product.v1.DeleteProductResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_v1_proto_init() }
func file_product_v1_proto_init() {
	if File_product_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_proto_rawDesc), len(file_product_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_proto_goTypes,
		DependencyIndexes: file_product_v1_proto_depIdxs,
		MessageInfos:      file_product_v1_proto_msgTypes,
	}.Build()
	File_product_v1_proto = out.File
	file_product_v1_proto_goTypes = nil
	file_product_v1_proto_depIdxs = nil
}
