// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: order_v1.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статусы заказа
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED        OrderStatus = 0  // Не указан
	OrderStatus_ORDER_STATUS_CREATED            OrderStatus = 1  // Заказ создан
	OrderStatus_ORDER_STATUS_PENDING_PAYMENT    OrderStatus = 2  // Ожидает оплаты
	OrderStatus_ORDER_STATUS_PAID               OrderStatus = 3  // Оплачен
	OrderStatus_ORDER_STATUS_PROCESSING         OrderStatus = 4  // В обработке
	OrderStatus_ORDER_STATUS_READY_FOR_SHIPMENT OrderStatus = 5  // Готов к отгрузке
	OrderStatus_ORDER_STATUS_SHIPPED            OrderStatus = 6  // Отправлен
	OrderStatus_ORDER_STATUS_IN_TRANSIT         OrderStatus = 7  // В пути
	OrderStatus_ORDER_STATUS_OUT_FOR_DELIVERY   OrderStatus = 8  // У курьера
	OrderStatus_ORDER_STATUS_DELIVERED          OrderStatus = 9  // Доставлен
	OrderStatus_ORDER_STATUS_CANCELLED          OrderStatus = 10 // Отменен
	OrderStatus_ORDER_STATUS_REFUNDED           OrderStatus = 11 // Возвращен
	OrderStatus_ORDER_STATUS_FAILED             OrderStatus = 12 // Не удался
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0:  "ORDER_STATUS_UNSPECIFIED",
		1:  "ORDER_STATUS_CREATED",
		2:  "ORDER_STATUS_PENDING_PAYMENT",
		3:  "ORDER_STATUS_PAID",
		4:  "ORDER_STATUS_PROCESSING",
		5:  "ORDER_STATUS_READY_FOR_SHIPMENT",
		6:  "ORDER_STATUS_SHIPPED",
		7:  "ORDER_STATUS_IN_TRANSIT",
		8:  "ORDER_STATUS_OUT_FOR_DELIVERY",
		9:  "ORDER_STATUS_DELIVERED",
		10: "ORDER_STATUS_CANCELLED",
		11: "ORDER_STATUS_REFUNDED",
		12: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":        0,
		"ORDER_STATUS_CREATED":            1,
		"ORDER_STATUS_PENDING_PAYMENT":    2,
		"ORDER_STATUS_PAID":               3,
		"ORDER_STATUS_PROCESSING":         4,
		"ORDER_STATUS_READY_FOR_SHIPMENT": 5,
		"ORDER_STATUS_SHIPPED":            6,
		"ORDER_STATUS_IN_TRANSIT":         7,
		"ORDER_STATUS_OUT_FOR_DELIVERY":   8,
		"ORDER_STATUS_DELIVERED":          9,
		"ORDER_STATUS_CANCELLED":          10,
		"ORDER_STATUS_REFUNDED":           11,
		"ORDER_STATUS_FAILED":             12,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_v1_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{0}
}

type SortBy int32

const (
	SortBy_SORT_BY_UNSPECIFIED  SortBy = 0
	SortBy_SORT_BY_CREATED_AT   SortBy = 1 // По дате создания
	SortBy_SORT_BY_UPDATED_AT   SortBy = 2 // По дате обновления
	SortBy_SORT_BY_TOTAL_AMOUNT SortBy = 3 // По сумме заказа
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_UNSPECIFIED",
		1: "SORT_BY_CREATED_AT",
		2: "SORT_BY_UPDATED_AT",
		3: "SORT_BY_TOTAL_AMOUNT",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_UNSPECIFIED":  0,
		"SORT_BY_CREATED_AT":   1,
		"SORT_BY_UPDATED_AT":   2,
		"SORT_BY_TOTAL_AMOUNT": 3,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_proto_enumTypes[1].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_order_v1_proto_enumTypes[1]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{1}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1 // По возрастанию
	SortOrder_SORT_ORDER_DESC        SortOrder = 2 // По убыванию
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_order_v1_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{2}
}

// Основное сообщение заказа
type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // Уникальный идентификатор
	PublicOrderNumber string                 `protobuf:"bytes,2,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"` // Публичный номер заказа
	UserId            uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                   // ID пользователя
	ProductId         uint32                 `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                          // ID товара
	Quantity          uint32                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                                             // Количество
	Status            OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`                       // Текущий статус
	TotalAmount       float32                `protobuf:"fixed32,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`                   // Общая сумма
	WarehouseId       uint32                 `protobuf:"varint,8,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`                    // ID склада (может быть 0 если не назначен)
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                           // Дата создания
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                          // Дата обновления
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetPublicOrderNumber() string {
	if x != nil {
		return x.PublicOrderNumber
	}
	return ""
}

func (x *Order) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Order) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetWarehouseId() uint32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Сообщение для создания заказа
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // ID пользователя
	ProductId     uint32                 `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`        // ID товара
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                           // Количество (должно быть > 0)
	TotalAmount   float32                `protobuf:"fixed32,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // Общая сумма
	WarehouseId   uint32                 `protobuf:"varint,6,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`  // ID склада (опционально)
	Status        OrderStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`     // Статус заказа (по умолчанию CREATED)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetWarehouseId() uint32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type CreateOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber string                 `protobuf:"bytes,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetPublicOrderNumber() string {
	if x != nil {
		return x.PublicOrderNumber
	}
	return ""
}

type GetOrdersByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserIdRequest) Reset() {
	*x = GetOrdersByUserIdRequest{}
	mi := &file_order_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIdRequest) ProtoMessage() {}

func (x *GetOrdersByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersByUserIdRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrdersByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserIdResponse) Reset() {
	*x = GetOrdersByUserIdResponse{}
	mi := &file_order_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIdResponse) ProtoMessage() {}

func (x *GetOrdersByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersByUserIdResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderByPublicOrderNumberRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber string                 `protobuf:"bytes,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderByPublicOrderNumberRequest) Reset() {
	*x = GetOrderByPublicOrderNumberRequest{}
	mi := &file_order_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByPublicOrderNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByPublicOrderNumberRequest) ProtoMessage() {}

func (x *GetOrderByPublicOrderNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByPublicOrderNumberRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByPublicOrderNumberRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderByPublicOrderNumberRequest) GetPublicOrderNumber() string {
	if x != nil {
		return x.PublicOrderNumber
	}
	return ""
}

type GetOrderByPublicOrderNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByPublicOrderNumberResponse) Reset() {
	*x = GetOrderByPublicOrderNumberResponse{}
	mi := &file_order_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByPublicOrderNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByPublicOrderNumberResponse) ProtoMessage() {}

func (x *GetOrderByPublicOrderNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByPublicOrderNumberResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByPublicOrderNumberResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderByPublicOrderNumberResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Сообщение для получения заказов по фильтрам
type GetOrdersByFiltersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // Номер страницы
	Limit uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Количество элементов на странице
	// Фильтры
	UserId      *uint32       `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`                  // Фильтр по пользователю
	ProductId   *uint32       `protobuf:"varint,4,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`         // Фильтр по товару
	WarehouseId *uint32       `protobuf:"varint,5,opt,name=warehouse_id,json=warehouseId,proto3,oneof" json:"warehouse_id,omitempty"`   // Фильтр по складу
	Statuses    []OrderStatus `protobuf:"varint,6,rep,packed,name=statuses,proto3,enum=order.v1.OrderStatus" json:"statuses,omitempty"` // Фильтр по статусам (можно несколько)
	// Диапазон дат
	CreatedFrom   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_from,json=createdFrom,proto3,oneof" json:"created_from,omitempty"`               // Создано с
	CreatedTo     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_to,json=createdTo,proto3,oneof" json:"created_to,omitempty"`                     // Создано по
	SortBy        SortBy                 `protobuf:"varint,9,opt,name=sort_by,json=sortBy,proto3,enum=order.v1.SortBy" json:"sort_by,omitempty"`              // Поле для сортировки
	SortOrder     SortOrder              `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3,enum=order.v1.SortOrder" json:"sort_order,omitempty"` // Направление сортировки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByFiltersRequest) Reset() {
	*x = GetOrdersByFiltersRequest{}
	mi := &file_order_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByFiltersRequest) ProtoMessage() {}

func (x *GetOrdersByFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByFiltersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByFiltersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersByFiltersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrdersByFiltersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrdersByFiltersRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetOrdersByFiltersRequest) GetProductId() uint32 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *GetOrdersByFiltersRequest) GetWarehouseId() uint32 {
	if x != nil && x.WarehouseId != nil {
		return *x.WarehouseId
	}
	return 0
}

func (x *GetOrdersByFiltersRequest) GetStatuses() []OrderStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *GetOrdersByFiltersRequest) GetCreatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedFrom
	}
	return nil
}

func (x *GetOrdersByFiltersRequest) GetCreatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTo
	}
	return nil
}

func (x *GetOrdersByFiltersRequest) GetSortBy() SortBy {
	if x != nil {
		return x.SortBy
	}
	return SortBy_SORT_BY_UNSPECIFIED
}

func (x *GetOrdersByFiltersRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// Ответ со списком заказов
type GetOrdersByFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`                            // Список заказов
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Общее количество заказов
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                               // Текущая страница
	TotalPages    uint32                 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // Общее количество страниц
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByFiltersResponse) Reset() {
	*x = GetOrdersByFiltersResponse{}
	mi := &file_order_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByFiltersResponse) ProtoMessage() {}

func (x *GetOrdersByFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByFiltersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByFiltersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrdersByFiltersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetOrdersByFiltersResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetOrdersByFiltersResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrdersByFiltersResponse) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Сообщение для обновления заказа
type UpdateOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber *string                `protobuf:"bytes,2,opt,name=public_order_number,json=publicOrderNumber,proto3,oneof" json:"public_order_number,omitempty"` // Публичный номер заказа
	UserId            *uint32                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`                                   // ID пользователя
	ProductId         *uint32                `protobuf:"varint,4,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`                          // ID товара
	Quantity          *uint32                `protobuf:"varint,5,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`                                             // Количество
	TotalAmount       *float32               `protobuf:"fixed32,6,opt,name=total_amount,json=totalAmount,proto3,oneof" json:"total_amount,omitempty"`                   // Общая сумма
	WarehouseId       *uint32                `protobuf:"varint,7,opt,name=warehouse_id,json=warehouseId,proto3,oneof" json:"warehouse_id,omitempty"`                    // ID склада
	Status            *OrderStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=order.v1.OrderStatus,oneof" json:"status,omitempty"`                       // Статус заказа
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_order_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrderRequest) GetPublicOrderNumber() string {
	if x != nil && x.PublicOrderNumber != nil {
		return *x.PublicOrderNumber
	}
	return ""
}

func (x *UpdateOrderRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *UpdateOrderRequest) GetProductId() uint32 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *UpdateOrderRequest) GetQuantity() uint32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *UpdateOrderRequest) GetTotalAmount() float32 {
	if x != nil && x.TotalAmount != nil {
		return *x.TotalAmount
	}
	return 0
}

func (x *UpdateOrderRequest) GetWarehouseId() uint32 {
	if x != nil && x.WarehouseId != nil {
		return *x.WarehouseId
	}
	return 0
}

func (x *UpdateOrderRequest) GetStatus() OrderStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type UpdateOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber string                 `protobuf:"bytes,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	mi := &file_order_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderResponse) GetPublicOrderNumber() string {
	if x != nil {
		return x.PublicOrderNumber
	}
	return ""
}

// Сообщение для изменения статуса заказа
type UpdateOrderStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber string                 `protobuf:"bytes,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"`
	NewStatus         OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=order.v1.OrderStatus" json:"new_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateOrderStatusRequest) GetPublicOrderNumber() string {
	if x != nil {
		return x.PublicOrderNumber
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type UpdateOrderStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber string                 `protobuf:"bytes,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"`
	NewStatus         OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=order.v1.OrderStatus" json:"new_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_order_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateOrderStatusResponse) GetPublicOrderNumber() string {
	if x != nil {
		return x.PublicOrderNumber
	}
	return ""
}

func (x *UpdateOrderStatusResponse) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

// Запрос статистики
type GetOrdersStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`        // Начальная дата
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`              // Конечная дата
	UserId        *uint32                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`                // Фильтр по пользователю (опционально)
	WarehouseId   *uint32                `protobuf:"varint,4,opt,name=warehouse_id,json=warehouseId,proto3,oneof" json:"warehouse_id,omitempty"` // Фильтр по складу (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersStatisticsRequest) Reset() {
	*x = GetOrdersStatisticsRequest{}
	mi := &file_order_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersStatisticsRequest) ProtoMessage() {}

func (x *GetOrdersStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrdersStatisticsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetOrdersStatisticsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetOrdersStatisticsRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetOrdersStatisticsRequest) GetWarehouseId() uint32 {
	if x != nil && x.WarehouseId != nil {
		return *x.WarehouseId
	}
	return 0
}

// Статистика по заказам
type GetOrdersStatisticsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders     uint32                 `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`                                                                                          // Всего заказов
	TotalRevenue    float32                `protobuf:"fixed32,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`                                                                                      // Общая выручка
	StatusCounts    map[string]uint32      `protobuf:"bytes,3,rep,name=status_counts,json=statusCounts,proto3" json:"status_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`             // Количество заказов по статусам
	UserOrderCounts map[uint32]uint32      `protobuf:"bytes,4,rep,name=user_order_counts,json=userOrderCounts,proto3" json:"user_order_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Количество заказов по пользователям
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrdersStatisticsResponse) Reset() {
	*x = GetOrdersStatisticsResponse{}
	mi := &file_order_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersStatisticsResponse) ProtoMessage() {}

func (x *GetOrdersStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrdersStatisticsResponse) GetTotalOrders() uint32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *GetOrdersStatisticsResponse) GetTotalRevenue() float32 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetOrdersStatisticsResponse) GetStatusCounts() map[string]uint32 {
	if x != nil {
		return x.StatusCounts
	}
	return nil
}

func (x *GetOrdersStatisticsResponse) GetUserOrderCounts() map[uint32]uint32 {
	if x != nil {
		return x.UserOrderCounts
	}
	return nil
}

// Сообщение для отмены заказа
type CancelOrderRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber  uint32                 `protobuf:"varint,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"`
	CancellationReason *string                `protobuf:"bytes,2,opt,name=cancellation_reason,json=cancellationReason,proto3,oneof" json:"cancellation_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{15}
}

func (x *CancelOrderRequest) GetPublicOrderNumber() uint32 {
	if x != nil {
		return x.PublicOrderNumber
	}
	return 0
}

func (x *CancelOrderRequest) GetCancellationReason() string {
	if x != nil && x.CancellationReason != nil {
		return *x.CancellationReason
	}
	return ""
}

// История изменений статуса заказа
type OrderStatusHistory struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	OrderId       uint32                             `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // ID заказа
	History       []*OrderStatusHistory_StatusChange `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`                 // История изменений
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusHistory) Reset() {
	*x = OrderStatusHistory{}
	mi := &file_order_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusHistory) ProtoMessage() {}

func (x *OrderStatusHistory) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusHistory.ProtoReflect.Descriptor instead.
func (*OrderStatusHistory) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{16}
}

func (x *OrderStatusHistory) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderStatusHistory) GetHistory() []*OrderStatusHistory_StatusChange {
	if x != nil {
		return x.History
	}
	return nil
}

// Запрос истории статусов
type GetOrderHistoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicOrderNumber uint32                 `protobuf:"varint,1,opt,name=public_order_number,json=publicOrderNumber,proto3" json:"public_order_number,omitempty"` // ID заказа
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderHistoryRequest) Reset() {
	*x = GetOrderHistoryRequest{}
	mi := &file_order_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryRequest) ProtoMessage() {}

func (x *GetOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{17}
}

func (x *GetOrderHistoryRequest) GetPublicOrderNumber() uint32 {
	if x != nil {
		return x.PublicOrderNumber
	}
	return 0
}

// Пустой ответ
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_order_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{18}
}

type OrderStatusHistory_StatusChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldStatus     OrderStatus            `protobuf:"varint,1,opt,name=old_status,json=oldStatus,proto3,enum=order.v1.OrderStatus" json:"old_status,omitempty"` // Старый статус
	NewStatus     OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=order.v1.OrderStatus" json:"new_status,omitempty"` // Новый статус
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`                            // Время изменения
	ChangedBy     string                 `protobuf:"bytes,4,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`                            // Кто изменил (user_id или система)
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                                   // Причина изменения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusHistory_StatusChange) Reset() {
	*x = OrderStatusHistory_StatusChange{}
	mi := &file_order_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusHistory_StatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusHistory_StatusChange) ProtoMessage() {}

func (x *OrderStatusHistory_StatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusHistory_StatusChange.ProtoReflect.Descriptor instead.
func (*OrderStatusHistory_StatusChange) Descriptor() ([]byte, []int) {
	return file_order_v1_proto_rawDescGZIP(), []int{16, 0}
}

func (x *OrderStatusHistory_StatusChange) GetOldStatus() OrderStatus {
	if x != nil {
		return x.OldStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderStatusHistory_StatusChange) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderStatusHistory_StatusChange) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *OrderStatusHistory_StatusChange) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *OrderStatusHistory_StatusChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_order_v1_proto protoreflect.FileDescriptor

const file_order_v1_proto_rawDesc = "" +
	"\n" +
	"\x0eorder_v1.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12.\n" +
	"\x13public_order_number\x18\x02 \x01(\tR\x11publicOrderNumber\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\rR\bquantity\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x02R\vtotalAmount\x12!\n" +
	"\fwarehouse_id\x18\b \x01(\rR\vwarehouseId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x02R\vtotalAmount\x12!\n" +
	"\fwarehouse_id\x18\x06 \x01(\rR\vwarehouseId\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\"E\n" +
	"\x13CreateOrderResponse\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\tR\x11publicOrderNumber\"3\n" +
	"\x18GetOrdersByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"D\n" +
	"\x19GetOrdersByUserIdResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\"T\n" +
	"\"GetOrderByPublicOrderNumberRequest\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\tR\x11publicOrderNumber\"N\n" +
	"#GetOrderByPublicOrderNumberResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\"\x91\x04\n" +
	"\x19GetOrdersByFiltersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\rH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"product_id\x18\x04 \x01(\rH\x01R\tproductId\x88\x01\x01\x12&\n" +
	"\fwarehouse_id\x18\x05 \x01(\rH\x02R\vwarehouseId\x88\x01\x01\x121\n" +
	"\bstatuses\x18\x06 \x03(\x0e2\x15.order.v1.OrderStatusR\bstatuses\x12B\n" +
	"\fcreated_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vcreatedFrom\x88\x01\x01\x12>\n" +
	"\n" +
	"created_to\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x04R\tcreatedTo\x88\x01\x01\x12)\n" +
	"\asort_by\x18\t \x01(\x0e2\x10.order.v1.SortByR\x06sortBy\x122\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x0e2\x13.order.v1.SortOrderR\tsortOrderB\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_product_idB\x0f\n" +
	"\r_warehouse_idB\x0f\n" +
	"\r_created_fromB\r\n" +
	"\v_created_to\"\x9b\x01\n" +
	"\x1aGetOrdersByFiltersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\rR\n" +
	"totalPages\"\x9d\x03\n" +
	"\x12UpdateOrderRequest\x123\n" +
	"\x13public_order_number\x18\x02 \x01(\tH\x00R\x11publicOrderNumber\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\rH\x01R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"product_id\x18\x04 \x01(\rH\x02R\tproductId\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x05 \x01(\rH\x03R\bquantity\x88\x01\x01\x12&\n" +
	"\ftotal_amount\x18\x06 \x01(\x02H\x04R\vtotalAmount\x88\x01\x01\x12&\n" +
	"\fwarehouse_id\x18\a \x01(\rH\x05R\vwarehouseId\x88\x01\x01\x122\n" +
	"\x06status\x18\b \x01(\x0e2\x15.order.v1.OrderStatusH\x06R\x06status\x88\x01\x01B\x16\n" +
	"\x14_public_order_numberB\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_product_idB\v\n" +
	"\t_quantityB\x0f\n" +
	"\r_total_amountB\x0f\n" +
	"\r_warehouse_idB\t\n" +
	"\a_status\"E\n" +
	"\x13UpdateOrderResponse\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\tR\x11publicOrderNumber\"\x80\x01\n" +
	"\x18UpdateOrderStatusRequest\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\tR\x11publicOrderNumber\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.order.v1.OrderStatusR\tnewStatus\"\x81\x01\n" +
	"\x19UpdateOrderStatusResponse\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\tR\x11publicOrderNumber\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.order.v1.OrderStatusR\tnewStatus\"\x97\x02\n" +
	"\x1aGetOrdersStatisticsRequest\x12>\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendDate\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\rH\x02R\x06userId\x88\x01\x01\x12&\n" +
	"\fwarehouse_id\x18\x04 \x01(\rH\x03R\vwarehouseId\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\n" +
	"\n" +
	"\b_user_idB\x0f\n" +
	"\r_warehouse_id\"\xb0\x03\n" +
	"\x1bGetOrdersStatisticsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\rR\vtotalOrders\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x02R\ftotalRevenue\x12\\\n" +
	"\rstatus_counts\x18\x03 \x03(\v27.order.v1.GetOrdersStatisticsResponse.StatusCountsEntryR\fstatusCounts\x12f\n" +
	"\x11user_order_counts\x18\x04 \x03(\v2:.order.v1.GetOrdersStatisticsResponse.UserOrderCountsEntryR\x0fuserOrderCounts\x1a?\n" +
	"\x11StatusCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aB\n" +
	"\x14UserOrderCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x92\x01\n" +
	"\x12CancelOrderRequest\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\rR\x11publicOrderNumber\x124\n" +
	"\x13cancellation_reason\x18\x02 \x01(\tH\x00R\x12cancellationReason\x88\x01\x01B\x16\n" +
	"\x14_cancellation_reason\"\xe3\x02\n" +
	"\x12OrderStatusHistory\x12\x19\n" +
	"\border_id\x18\x01 \x01(\rR\aorderId\x12C\n" +
	"\ahistory\x18\x02 \x03(\v2).order.v1.OrderStatusHistory.StatusChangeR\ahistory\x1a\xec\x01\n" +
	"\fStatusChange\x124\n" +
	"\n" +
	"old_status\x18\x01 \x01(\x0e2\x15.order.v1.OrderStatusR\toldStatus\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.order.v1.OrderStatusR\tnewStatus\x129\n" +
	"\n" +
	"changed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x04 \x01(\tR\tchangedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"H\n" +
	"\x16GetOrderHistoryRequest\x12.\n" +
	"\x13public_order_number\x18\x01 \x01(\rR\x11publicOrderNumber\"\x0f\n" +
	"\rEmptyResponse*\x86\x03\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x01\x12 \n" +
	"\x1cORDER_STATUS_PENDING_PAYMENT\x10\x02\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x03\x12\x1b\n" +
	"\x17ORDER_STATUS_PROCESSING\x10\x04\x12#\n" +
	"\x1fORDER_STATUS_READY_FOR_SHIPMENT\x10\x05\x12\x18\n" +
	"\x14ORDER_STATUS_SHIPPED\x10\x06\x12\x1b\n" +
	"\x17ORDER_STATUS_IN_TRANSIT\x10\a\x12!\n" +
	"\x1dORDER_STATUS_OUT_FOR_DELIVERY\x10\b\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\t\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\n" +
	"\x12\x19\n" +
	"\x15ORDER_STATUS_REFUNDED\x10\v\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\f*k\n" +
	"\x06SortBy\x12\x17\n" +
	"\x13SORT_BY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_BY_CREATED_AT\x10\x01\x12\x16\n" +
	"\x12SORT_BY_UPDATED_AT\x10\x02\x12\x18\n" +
	"\x14SORT_BY_TOTAL_AMOUNT\x10\x03*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x022\x8d\x05\n" +
	"\x0eOrderV1Service\x12J\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\x12_\n" +
	"\x14GetAllOrdersByUserId\x12\".order.v1.GetOrdersByUserIdRequest\x1a#.order.v1.GetOrdersByUserIdResponse\x12z\n" +
	"\x1bGetOrderByPublicOrderNumber\x12,.order.v1.GetOrderByPublicOrderNumberRequest\x1a-.order.v1.GetOrderByPublicOrderNumberResponse\x12b\n" +
	"\x15GetAllOrdersByFilters\x12#.order.v1.GetOrdersByFiltersRequest\x1a$.order.v1.GetOrdersByFiltersResponse\x12J\n" +
	"\vUpdateOrder\x12\x1c.order.v1.UpdateOrderRequest\x1a\x1d.order.v1.UpdateOrderResponse\x12\\\n" +
	"\x11UpdateOrderStatus\x12\".order.v1.UpdateOrderStatusRequest\x1a#.order.v1.UpdateOrderStatusResponse\x12D\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x17.order.v1.EmptyResponseB\x1cZ\x1apkg/order/order_v1;orderv1b\x06proto3"

var (
	file_order_v1_proto_rawDescOnce sync.Once
	file_order_v1_proto_rawDescData []byte
)

func file_order_v1_proto_rawDescGZIP() []byte {
	file_order_v1_proto_rawDescOnce.Do(func() {
		file_order_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_proto_rawDesc), len(file_order_v1_proto_rawDesc)))
	})
	return file_order_v1_proto_rawDescData
}

var file_order_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_order_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_order_v1_proto_goTypes = []any{
	(OrderStatus)(0),                            // 0: order.v1.OrderStatus
	(SortBy)(0),                                 // 1: order.v1.SortBy
	(SortOrder)(0),                              // 2: order.v1.SortOrder
	(*Order)(nil),                               // 3: order.v1.Order
	(*CreateOrderRequest)(nil),                  // 4: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),                 // 5: order.v1.CreateOrderResponse
	(*GetOrdersByUserIdRequest)(nil),            // 6: order.v1.GetOrdersByUserIdRequest
	(*GetOrdersByUserIdResponse)(nil),           // 7: order.v1.GetOrdersByUserIdResponse
	(*GetOrderByPublicOrderNumberRequest)(nil),  // 8: order.v1.GetOrderByPublicOrderNumberRequest
	(*GetOrderByPublicOrderNumberResponse)(nil), // 9: order.v1.GetOrderByPublicOrderNumberResponse
	(*GetOrdersByFiltersRequest)(nil),           // 10: order.v1.GetOrdersByFiltersRequest
	(*GetOrdersByFiltersResponse)(nil),          // 11: order.v1.GetOrdersByFiltersResponse
	(*UpdateOrderRequest)(nil),                  // 12: order.v1.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),                 // 13: order.v1.UpdateOrderResponse
	(*UpdateOrderStatusRequest)(nil),            // 14: order.v1.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil),           // 15: order.v1.UpdateOrderStatusResponse
	(*GetOrdersStatisticsRequest)(nil),          // 16: order.v1.GetOrdersStatisticsRequest
	(*GetOrdersStatisticsResponse)(nil),         // 17: order.v1.GetOrdersStatisticsResponse
	(*CancelOrderRequest)(nil),                  // 18: order.v1.CancelOrderRequest
	(*OrderStatusHistory)(nil),                  // 19: order.v1.OrderStatusHistory
	(*GetOrderHistoryRequest)(nil),              // 20: order.v1.GetOrderHistoryRequest
	(*EmptyResponse)(nil),                       // 21: order.v1.EmptyResponse
	nil,                                         // 22: order.v1.GetOrdersStatisticsResponse.StatusCountsEntry
	nil,                                         // 23: order.v1.GetOrdersStatisticsResponse.UserOrderCountsEntry
	(*OrderStatusHistory_StatusChange)(nil),     // 24: order.v1.OrderStatusHistory.StatusChange
	(*timestamppb.Timestamp)(nil),               // 25: google.protobuf.Timestamp
}
var file_order_v1_proto_depIdxs = []int32{
	0,  // 0: order.v1.Order.status:type_name -> order.v1.OrderStatus
	25, // 1: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	25, // 2: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: order.v1.CreateOrderRequest.status:type_name -> order.v1.OrderStatus
	3,  // 4: order.v1.GetOrdersByUserIdResponse.orders:type_name -> order.v1.Order
	3,  // 5: order.v1.GetOrderByPublicOrderNumberResponse.orders:type_name -> order.v1.Order
	0,  // 6: order.v1.GetOrdersByFiltersRequest.statuses:type_name -> order.v1.OrderStatus
	25, // 7: order.v1.GetOrdersByFiltersRequest.created_from:type_name -> google.protobuf.Timestamp
	25, // 8: order.v1.GetOrdersByFiltersRequest.created_to:type_name -> google.protobuf.Timestamp
	1,  // 9: order.v1.GetOrdersByFiltersRequest.sort_by:type_name -> order.v1.SortBy
	2,  // 10: order.v1.GetOrdersByFiltersRequest.sort_order:type_name -> order.v1.SortOrder
	3,  // 11: order.v1.GetOrdersByFiltersResponse.orders:type_name -> order.v1.Order
	0,  // 12: order.v1.UpdateOrderRequest.status:type_name -> order.v1.OrderStatus
	0,  // 13: order.v1.UpdateOrderStatusRequest.new_status:type_name -> order.v1.OrderStatus
	0,  // 14: order.v1.UpdateOrderStatusResponse.new_status:type_name -> order.v1.OrderStatus
	25, // 15: order.v1.GetOrdersStatisticsRequest.start_date:type_name -> google.protobuf.Timestamp
	25, // 16: order.v1.GetOrdersStatisticsRequest.end_date:type_name -> google.protobuf.Timestamp
	22, // 17: order.v1.GetOrdersStatisticsResponse.status_counts:type_name -> order.v1.GetOrdersStatisticsResponse.StatusCountsEntry
	23, // 18: order.v1.GetOrdersStatisticsResponse.user_order_counts:type_name -> order.v1.GetOrdersStatisticsResponse.UserOrderCountsEntry
	24, // 19: order.v1.OrderStatusHistory.history:type_name -> order.v1.OrderStatusHistory.StatusChange
	0,  // 20: order.v1.OrderStatusHistory.StatusChange.old_status:type_name -> order.v1.OrderStatus
	0,  // 21: order.v1.OrderStatusHistory.StatusChange.new_status:type_name -> order.v1.OrderStatus
	25, // 22: order.v1.OrderStatusHistory.StatusChange.changed_at:type_name -> google.protobuf.Timestamp
	4,  // 23: order.v1.OrderV1Service.CreateOrder:input_type -> order.v1.CreateOrderRequest
	6,  // 24: order.v1.OrderV1Service.GetAllOrdersByUserId:input_type -> order.v1.GetOrdersByUserIdRequest
	8,  // 25: order.v1.OrderV1Service.GetOrderByPublicOrderNumber:input_type -> order.v1.GetOrderByPublicOrderNumberRequest
	10, // 26: order.v1.OrderV1Service.GetAllOrdersByFilters:input_type -> order.v1.GetOrdersByFiltersRequest
	12, // 27: order.v1.OrderV1Service.UpdateOrder:input_type -> order.v1.UpdateOrderRequest
	14, // 28: order.v1.OrderV1Service.UpdateOrderStatus:input_type -> order.v1.UpdateOrderStatusRequest
	18, // 29: order.v1.OrderV1Service.CancelOrder:input_type -> order.v1.CancelOrderRequest
	5,  // 30: order.v1.OrderV1Service.CreateOrder:output_type -> order.v1.CreateOrderResponse
	7,  // 31: order.v1.OrderV1Service.GetAllOrdersByUserId:output_type -> order.v1.GetOrdersByUserIdResponse
	9,  // 32: order.v1.OrderV1Service.GetOrderByPublicOrderNumber:output_type -> order.v1.GetOrderByPublicOrderNumberResponse
	11, // 33: order.v1.OrderV1Service.GetAllOrdersByFilters:output_type -> order.v1.GetOrdersByFiltersResponse
	13, // 34: order.v1.OrderV1Service.UpdateOrder:output_type -> order.v1.UpdateOrderResponse
	15, // 35: order.v1.OrderV1Service.UpdateOrderStatus:output_type -> order.v1.UpdateOrderStatusResponse
	21, // 36: order.v1.OrderV1Service.CancelOrder:output_type -> order.v1.EmptyResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_order_v1_proto_init() }
func file_order_v1_proto_init() {
	if File_order_v1_proto != nil {
		return
	}
	file_order_v1_proto_msgTypes[7].OneofWrappers = []any{}
	file_order_v1_proto_msgTypes[9].OneofWrappers = []any{}
	file_order_v1_proto_msgTypes[13].OneofWrappers = []any{}
	file_order_v1_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_proto_rawDesc), len(file_order_v1_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_proto_goTypes,
		DependencyIndexes: file_order_v1_proto_depIdxs,
		EnumInfos:         file_order_v1_proto_enumTypes,
		MessageInfos:      file_order_v1_proto_msgTypes,
	}.Build()
	File_order_v1_proto = out.File
	file_order_v1_proto_goTypes = nil
	file_order_v1_proto_depIdxs = nil
}
